services:
    web:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html/
        container_name: ign633-nigeria-website
        ports:
            - 80:80
